<%
  case ENV['TEST_KITCHEN_PROVIDER']
    when 'digitalocean'
      @tc_provider = 'digitalocean'
      puts 'Using DigitalOcean provider'
    when 'vagrant'
      @tc_provider = 'vagrant'
      puts 'Using vagrant provider'
    else
      puts "Unknown provider \'#{ENV['TEST_KITCHEN_PROVIDER']}\', using vagrant provider"
      @tc_provider = 'vagrant'
  end
%>

<% case @tc_provider 
     when 'digitalocean'
%>
---
driver:
  name: digitalocean
  region: sgp1
  size: 512mb

provisioner:
  name: chef_solo

platforms:
  - name: debian-7-0-x64

suites:
- name: default
  run_list:
    - recipe[logentries_ng_test_helper]
  attributes:
    logentries:
      account_key: <%= ENV['LOGENTRIES_API_KEY'] %>
<% when 'vagrant' %>
---
driver_plugin: vagrant

platforms:
- name:  debian-7.4
  driver:
    provider: virtualbox
    customize:
      memory: 1024

suites:
- name: default
  run_list:
    - recipe[logentries_ng_test_helper]
  attributes:
    logentries:
      account_key: <%= ENV['LOGENTRIES_API_KEY'] %>
<% end %>
